const Task = {
    ATTACK: 0,
    ATTACK_CONTROLLER: 1,
    BUILD: 2,
    CLAIM_CONTROLLER: 3,
    DISMANTLE: 4,
    DROP: 5,
    GENERATE_SAFE_MODE: 6,
    HARVEST: 7,
    HEAL: 8,
    MOVE: 9,
    PICKUP: 10,
    PULL: 11,
    RANGED_ATTACK: 12,
    RANGED_HEAL : 13,
    RANGED_MASS_ATTACK: 14,
    REPAIR: 15,
    RESERVE_CONTROLLER: 16,
    SIGN_CONTROLLER: 17,
    TRANSFER: 18,
    UPGRADE_CONTROLLER: 19,
    WITHDRAW: 20,

    CONTINUING_MOVE: 21,
}



module.exports = Task;